[package]
name = "smoke"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
anyhow = "1"
jupyter-protocol = "0.3.0"
jupyter-websocket-client = "0.5.0"
mybinder = "0.1.0"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
