name: Smokey the Binder

on:
  schedule:
    - cron: "7,37 * * * *"

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  smoke:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: cargo build --verbose
      - name: Run
        run: cargo run
