name: Smokey the Binder

on:
  schedule:
    - cron: "7,22,37,52 * * * *"

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev

      - name: Build
        run: cargo build --verbose
      - name: Run
        run: cargo run
